# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubervu}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Radu Spineanu"]
  s.date = %q{2010-05-05}
  s.description = %q{Library for accessing the UberVU.com and ContextVoice.com API.}
  s.email = %q{radu@2performant.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "README",
     "Rakefile",
     "VERSION",
     "lib/rubervu.rb",
     "lib/rubervu/ubervu.rb",
     "lib/rubervu/ubervu_reaction.rb",
     "lib/rubervu/ubervu_resource.rb",
     "rubervu.gemspec"
  ]
  s.homepage = %q{http://github.com/sradu/Rubervu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Library for accessing the UberVU.com and ContextVoice.com API.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

